
package com.terminal.api.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TerminalesSuperTransporte", targetNamespace = "urn:SPTCDAwsdl", wsdlLocation = "http://aplicaciones.supertransporte.gov.co/service_Terminales?wsdl")
public class TerminalesSuperTransporte
    extends Service
{

    private final static URL TERMINALESSUPERTRANSPORTE_WSDL_LOCATION;
    private final static WebServiceException TERMINALESSUPERTRANSPORTE_EXCEPTION;
    private final static QName TERMINALESSUPERTRANSPORTE_QNAME = new QName("urn:SPTCDAwsdl", "TerminalesSuperTransporte");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://aplicaciones.supertransporte.gov.co/service_Terminales?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TERMINALESSUPERTRANSPORTE_WSDL_LOCATION = url;
        TERMINALESSUPERTRANSPORTE_EXCEPTION = e;
    }

    public TerminalesSuperTransporte() {
        super(__getWsdlLocation(), TERMINALESSUPERTRANSPORTE_QNAME);
    }

    public TerminalesSuperTransporte(WebServiceFeature... features) {
        super(__getWsdlLocation(), TERMINALESSUPERTRANSPORTE_QNAME, features);
    }

    public TerminalesSuperTransporte(URL wsdlLocation) {
        super(wsdlLocation, TERMINALESSUPERTRANSPORTE_QNAME);
    }

    public TerminalesSuperTransporte(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TERMINALESSUPERTRANSPORTE_QNAME, features);
    }

    public TerminalesSuperTransporte(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TerminalesSuperTransporte(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TerminalesSuperTransportePortType
     */
    @WebEndpoint(name = "TerminalesSuperTransportePort")
    public TerminalesSuperTransportePortType getTerminalesSuperTransportePort() {
        return super.getPort(new QName("urn:SPTCDAwsdl", "TerminalesSuperTransportePort"), TerminalesSuperTransportePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TerminalesSuperTransportePortType
     */
    @WebEndpoint(name = "TerminalesSuperTransportePort")
    public TerminalesSuperTransportePortType getTerminalesSuperTransportePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:SPTCDAwsdl", "TerminalesSuperTransportePort"), TerminalesSuperTransportePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TERMINALESSUPERTRANSPORTE_EXCEPTION!= null) {
            throw TERMINALESSUPERTRANSPORTE_EXCEPTION;
        }
        return TERMINALESSUPERTRANSPORTE_WSDL_LOCATION;
    }

}
